image:
  repository: "<REGION>-docker.pkg.dev/<PROJECT_ID>/hello-repo/hello-flask"
  tag: "dev"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

env:
  - name: WHO
    value: "gke"

podSecurityContext:
  runAsUser: 10001
  runAsNonRoot: true
  fsGroup: 10001

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

readinessProbe:
  httpGet: { path: /healthz, port: 8080 }
  initialDelaySeconds: 3
  periodSeconds: 10

livenessProbe:
  httpGet: { path: /healthz, port: 8080 }
  initialDelaySeconds: 10
  periodSeconds: 20

enableServiceMonitor: false

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
