name: CI Smoke

on:
  push:
    branches: [ "main" ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Actions are working on $GITHUB_REF at $GITHUB_SHA"
